# Generated by Django 4.1.5 on 2023-01-26 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registereddetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registereddetails.gender'),
        ),
    ]
